var ResourceRole=function(){
	this.resource_role_grid_id='',
	this.setting=function(resource_role_grid_id){
		this.resource_role_grid_id=resource_role_grid_id;
	},
	this.getResourceRoleGrid=function(){
		return $('#'+this.resource_role_grid_id);
	},
	this.resourceRoleGridInit=function(){
		this.getResourceRoleGrid().treegrid({
			url:'roleInfoSysResourceList.do',
			idField:'prefix',
			treeField:'name',
			fit:true,
			fitColumns:true,
			border:false,
			rownumbers:true,
			pagination:true,
			pageSize:2,
			pageList:[2,4,6,8],
			pageNumber:1,
			columns:[[{
				title:'编号',
				field:'id',
				width:'20%',
				hidden:true
			},{
				title:'名称',
				field:'name',
				width:'20%'
			},{
				title:'标识',
				field:'prefix',
				width:'20%'
			},{
				title:'角色描述',
				field:'roleDescription',
				width:'20%'
			},{
				title:'资源描述',
				field:'sysResourceDescription',
				width:'20%'
			}]]
		});
	},
	this.init=function(){
		this.resourceRoleGridInit();
	}
}